'use client';
import { useState, useEffect, useRef } from 'react';
import Link from 'next/link';
import { api } from '@/lib/api';
import { FiFileText, FiDownload, FiEye, FiTrash2, FiBarChart2 } from 'react-icons/fi';

export default function ReportsPage() {
  const [reports, setReports] = useState<any[]>([]);
  const [resumes, setResumes] = useState<any[]>([]);
  const [jobs, setJobs] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedResume, setSelectedResume] = useState('');
  const [selectedJob, setSelectedJob] = useState('');
  const [generating, setGenerating] = useState(false);
  const printRef = useRef<HTMLDivElement>(null);

  const loadData = async () => {
    try {
      const [rpt, res, jbs] = await Promise.all([
        api.reports.getAll().catch(() => []),
        api.resumes.getAll().catch(() => []),
        api.jobs.getAll().catch(() => []),
      ]);
      setReports(rpt);
      setResumes(res);
      setJobs(jbs);
    } catch {}
    setLoading(false);
  };

  useEffect(() => { loadData(); }, []);

  const handleGenerate = async () => {
    if (!selectedResume) return;
    setGenerating(true);
    try {
      await api.reports.generate(selectedResume, selectedJob || undefined);
      await loadData();
      setSelectedResume(''); setSelectedJob('');
    } catch (err: any) {
      alert(err.message);
    }
    setGenerating(false);
  };

  const handlePrint = (report: any) => {
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(`
      <html><head><title>SkillBridge AI Report</title>
      <style>body{font-family:system-ui;padding:40px;max-width:800px;margin:auto}
      h1{color:#2563eb}h2{color:#374151;margin-top:24px}
      .score{font-size:48px;font-weight:bold;color:#2563eb}
      .suggestions{background:#f3f4f6;padding:16px;border-radius:8px;margin:16px 0}
      .skills{display:flex;flex-wrap:wrap;gap:8px}
      .skills span{background:#dbeafe;color:#1e40af;padding:4px 12px;border-radius:999px;font-size:13px}
      </style></head><body>
      <h1>SkillBridge AI - Analysis Report</h1>
      <p>Generated: ${new Date(report.createdAt).toLocaleString()}</p>
      ${report.atsScore ? `<div style="margin:24px 0"><h2>ATS Score</h2><div class="score">${report.atsScore.overall}/100</div></div>` : ''}
      ${report.matchScore !== undefined ? `<div><h2>Match Score</h2><div class="score">${report.matchScore}%</div></div>` : ''}
      ${report.missingSkills.length > 0 ? `<div><h2>Missing Skills</h2><div class="skills">${report.missingSkills.map((s:string) => `<span>${s}</span>`).join('')}</div></div>` : ''}
      ${report.recommendations.length > 0 ? `<div><h2>Recommendations</h2><div class="suggestions">${report.recommendations.map((r:string) => `<p>${r}</p>`).join('')}</div></div>` : ''}
      ${report.learningRoadmap ? `<div><h2>Learning Roadmap</h2>${report.learningRoadmap.weeks.map((w:any) => `<div style="margin:8px 0"><strong>Week ${w.weekNumber}: ${w.title}</strong></div>`).join('')}</div>` : ''}
      <hr style="margin-top:40px"><p style="color:#9ca3af;font-size:12px">Generated by SkillBridge AI</p>
      </body></html>
    `);
    win.document.close();
    win.print();
  };

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-gray-900">Reports</h1>

      <div className="bg-white rounded-xl border border-gray-200 p-6">
        <h2 className="text-sm font-semibold text-gray-900 mb-4 flex items-center gap-2">
          <FiBarChart2 size={18} /> Generate New Report
        </h2>
        <div className="grid md:grid-cols-3 gap-4 mb-4">
          <select value={selectedResume} onChange={e => setSelectedResume(e.target.value)}
            className="px-3 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none text-sm bg-white">
            <option value="">Select Resume *</option>
            {resumes.map(r => <option key={r.id} value={r.id}>{r.fileName}</option>)}
          </select>
          <select value={selectedJob} onChange={e => setSelectedJob(e.target.value)}
            className="px-3 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none text-sm bg-white">
            <option value="">Select Job (optional)</option>
            {jobs.map(j => <option key={j.id} value={j.id}>{j.title}</option>)}
          </select>
          <button onClick={handleGenerate} disabled={!selectedResume || generating}
            className="px-4 py-2.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 text-sm font-medium transition-colors">
            {generating ? 'Generating...' : 'Generate Report'}
          </button>
        </div>
      </div>

      {loading ? (
        <div className="text-center py-12 text-gray-400">Loading...</div>
      ) : reports.length === 0 ? (
        <div className="bg-white rounded-xl border border-gray-200 p-12 text-center">
          <FiFileText className="w-16 h-16 mx-auto text-gray-300 mb-4" />
          <h2 className="text-xl font-semibold text-gray-900 mb-2">No reports yet</h2>
          <p className="text-gray-500">Select a resume and optional job to generate your first report</p>
        </div>
      ) : (
        <div className="space-y-3">
          {reports.map(r => (
            <div key={r.id} className="bg-white rounded-xl border border-gray-200 p-5 hover:shadow-md transition-shadow">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <FiFileText className="text-blue-600" size={24} />
                  <div>
                    <p className="text-sm font-medium text-gray-900">
                      Report &middot; {new Date(r.createdAt).toLocaleDateString()}
                    </p>
                    <div className="flex items-center gap-3 mt-1">
                      {r.atsScore && (
                        <span className={`text-sm font-bold ${r.atsScore.overall >= 70 ? 'text-green-600' : 'text-yellow-600'}`}>
                          ATS: {r.atsScore.overall}/100
                        </span>
                      )}
                      {r.matchScore !== undefined && (
                        <span className={`text-sm font-bold ${r.matchScore >= 70 ? 'text-green-600' : r.matchScore >= 40 ? 'text-yellow-600' : 'text-red-600'}`}>
                          Match: {r.matchScore}%
                        </span>
                      )}
                      <span className="text-xs text-gray-400">{r.missingSkills.length} missing skills</span>
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <button onClick={() => handlePrint(r)}
                    className="flex items-center gap-1 px-3 py-1.5 border border-gray-300 rounded-lg hover:bg-gray-50 text-xs font-medium text-gray-700 transition-colors">
                    <FiDownload size={14} /> Print
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
